#!/bin/bash
# Start LAMP image
#sudo docker run -d \

sudo docker run -d \
	-v /home/jorge/git-repos/php-mercadopago:/srv/http \
       -v /home/jorge/php:/etc/php \
	--name lamp \
	-p 80:80 \
	-p 443:443 greyltc/lamp
