#!/usr/bin/env python
#
import subprocess
import sys,os

print sys.argv[0]
fdir, fname = os.path.split(sys.argv[0])
print fdir

# read all files
timestamps = []
for root, dirs, files in os.walk(fdir):
	for file in files:
		if file[0:12] == 'valente_prod':
			if not file[13:25] in timestamps:
				timestamps.append(file[13:25])


timestmp = timestamps[len(timestamps)-1]


params = 'drive upload {}/valente_prod_{}.dump -p 0B6VdvqXtEoYANWhhUzhoU0xTVDg'.format(fdir,timestmp)
print params
subprocess.call(params, shell=True)
params = 'drive upload {}/valente_prod_{}.tar -p 0B6VdvqXtEoYANWhhUzhoU0xTVDg'.format(fdir,timestmp)
subprocess.call(params, shell=True)

#vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
